### ISSUE TITLE
API timeout issue

### ISSUE THREAD

**Issue by topninja** [hflabs/dadata-php#5]
I tried to follow steps but shows this.

GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 3000 milliseconds (see 
https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cleaner.dadata.ru/api/v1/clean/address in file E:\WORK\Web\MPC\backend\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 210

Looks like timout is small.

**Comment by nalgeon** [comment]
3 seconds timeout is just fine. Connection timeout exception suggests that there is a network problem.
